gretchen:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10  

  head_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - pan_joint
      - tilt_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

